version: '3.9'

services:
  cpu:
    container_name: ginger
    working_dir: /gingerbread
    user: $DOCKER_USER
    image: neomedsys01/gingerbread:latest

    env_file:
      - environment.env
      
    volumes:
      - .:/gingerbread

    stdin_open: true # docker run -i
    tty: true # docker run -t
  

  gpu:
    container_name: ginger
    working_dir: /gingerbread
    user: $DOCKER_USER
    image: neomedsys01/gingerbread:latest

    env_file:
      - environment.env

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    volumes:
      - .:/gingerbread

    stdin_open: true # docker run -i
    tty: true # docker run -t

