version: '3.9'

services:
  dev_gpu:
    image: neomedsys01/gingerbread:latest

    env_file:
      - environment.env

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    volumes:
      - .:/gingerbread

    stdin_open: true # docker run -i
    tty: true # docker run -t
