name: Building_docs

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test_docker_compose:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and test
        id: docker_log
        run: |
          docker compose -f ginger-cpu.yml up -d
          echo "LOG FROM CONTAINER: \n" >> /home/runner/work/Gingerbread_sc/Gingerbread_sc/.github/workflows/comment.md
          echo "$(docker-compose logs test_service)" >> /home/runner/work/Gingerbread_sc/Gingerbread_sc/.github/workflows/comment.md
          docker-compose down

      - name: post PR comment with docker logs
        uses: NejcZdovc/comment-pr@v2
        with:
          file: "comment.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  doc_building:
    needs: test_docker_compose
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install
      - run: poetry run sphinx-apidoc -o docs .
      - run: cd docs && poetry run make html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
